import os

ANNOUNCEMENTS_CHAT = os.getenv("ANNOUNCEMENTS_CHAT")
ANNOUNCEMENTS_TOPIC = int(os.getenv("ANNOUNCEMENTS_TOPIC", "0")) or None
REFRESH_INTERVAL_MINUTES = int(os.getenv("REFRESH_INTERVAL_MINUTES", "15"))
